### ISSUE TITLE
No more one unit at same tile

### ISSUE THREAD

**Issue by buxx** [buxx/OpenCombat#12]
We cannot place more than one unit at same tile:

* When a position change will be done, verify before if it is free (take care: computing process are parallelized, use share memory for this ?)
* More than one tile units have to be managed: a tank take more than one tile !

**Comment by tomlowshang** [comment]
What is the size of a tile in metres?

**Comment by buxx** [comment]
For now, i think to use 1 meter by tile. So 0,125 meters by pixel.

**Comment by tomlowshang** [comment]
Note that at 1 meter per tile, a prone man occupies two tiles.

**Comment by buxx** [comment]
You're right. In really, i don't know if it will be a problem but i think (for the moment) it can be playable to have "very near" soldiers: 

![capture du 2018-01-29 21-46-53](https://user-images.githubusercontent.com/1104637/35533558-34ee805c-053e-11e8-8f94-2fceac3f05d7.png)

But, i will have to code the "occupied tiles" by large units like tank, so it wil be possible to code it for prone soldiers.
