### ISSUE TITLE
Test environment setup is unclear

### ISSUE THREAD

**Issue by panjacek** [buxx/OpenCombat#53]
Issues:
- requirements.txt  does not contain all dependencies
- pytest still fails to run after installation of python items from requirements and readme (missing redis)
- no info on redis, how to setup for test.

Possible solutions:
- Consider usage of docker-compose.yml and dockerfile to define the environment for test.

**Comment by panjacek** [comment]
After some debug I've realized that dependency library has hardcoded values for redis and thats why docker-compose.yml with server as service did not work.
` self._r = redis.StrictRedis(host='localhost', port=6379, db=0) # TODO: configs`

**Comment by panjacek** [comment]
More I look at requirements.txt and instructions, more confused I am.

- I've cleaned requirements.txt which contained a lot of synergine or cocos items.
- created feature branch on my fork.
https://github.com/panjacek/OpenCombat/tree/feature/docker_env

Now you can run the tests via
`
#on a first run
docker-compose build

#any successive run will use your repo mounted
make pytest`

**Comment by buxx** [comment]
Hello @panjacek i miss your issue since years ! I restart the project. Are you still here ?

**Comment by buxx** [comment]
Hello, since this issue game have been rewrite It's Rust.
