### ISSUE TITLE
Similar attempt from 2005?

### ISSUE THREAD

**Issue by commel** [buxx/OpenCombat#73]
Is this project similar to this 2005 attempt of a Close Combat clone? 

https://sourceforge.net/projects/adv-warfare/ 

Maybe some old resources can be shared (GPLv2 and GPLv3)?

**Comment by buxx** [comment]
Hello @commel , nice find, I didn't know !
I will take a look ! I hope graphical resources are gpl !

**Comment by buxx** [comment]
There is a lot of work in this project. It can be very interesting to look into. Sadly, graphics resources are not included, i think this code use the official CC graphic and sound resources.

**Comment by commel** [comment]
There are quite some tga files in the build-20051201. Do you think these are the original assets from the commercial game? I've migrated the sources from CVS to git and put them here: https://github.com/commel/opencombat2005. Hope this helps somehow :)

**Comment by buxx** [comment]
Thanks for migration ! I seen commercial game tga files some weeks ago and yes, they are very similar ... :(
